name: Run tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: execute
jobs:
  gradle:
    runs-on: ubuntu-latestz
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Makes gradle accessible to Github action
        run: chmod +x gradlew

      - name: Execute build & test
        run: ./gradlew build --scan
